name: Build transformer develop image
on:
  push:
    branches:
      - 'develop'
env:
  REPO_NAME_OLD: rudderlabs/develop-rudder-transformer
  REPO_NAME: rudderstack/develop-rudder-transformer
  DOCKERHUB_USERNAME: rudderlabs
  GITHUB_TOKEN: 'build-deploy-pkey'
  MAIL: 'mail-id'
  USER_NAME: 'user-name'

jobs:
  transformer-build:
    name: Build transformer develop image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get image version
        id: get_version
        run: |
          VERSION="develop"
          echo $VERSION
          echo "::set-output name=version::$VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          load: true
          tags: |
            ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }} npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-platform images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REPO_NAME_OLD }}:${{ steps.get_version.outputs.version }}
            ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ steps.get_version.outputs.version }}
            COMMIT_HASH=${{ github.sha }}

  user-transformer-build:
    name: Build user transformer develop image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get image version
        id: get_version
        run: |
          VERSION="ut-develop"
          echo $VERSION
          echo "::set-output name=version::$VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-ut-func
          load: true
          tags: |
            ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }} npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-platform images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-ut-func
          push: true
          tags: |
            ${{ env.REPO_NAME_OLD }}:${{ steps.get_version.outputs.version }}
            ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ steps.get_version.outputs.version }}
            COMMIT_HASH=${{ github.sha }}

  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        run: |
          git clone https://${{secrets.GITHUB_TOKEN}}@github.com/rudderlabs/rudder-devops.git
          git config --global user.email \"${{env.MAIL}}\"
          git config --global user.name \"${{env.USER_NAME}}\"
          cd rudder-devops/helm-charts/shared-services/per-az
          git checkout -b shared-transformer-$VERSION
          yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.blue-release.yaml
          yq eval -i ".user-transformer.image.tag=\"$VERSION\"" values.blue-release.yaml
          yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.prod.yaml
          yq eval -i ".user-transformer.image.tag=\"$VERSION\"" values.prod.yaml
          git add values.blue-release.yaml values.prod.yaml
          cd ../../config-be-rudder-transformer
          yq eval -i ".config-be-rudder-transformer.image.tag=\"$VERSION\"" values.prod.yaml
          yq eval -i ".config-be-user-transformer.image.tag=\"$VERSION\"" values.prod.yaml
          git add values.prod.yaml
          git commit -m "changing version for shared transformer"
          git push -u origin shared-transformer-$VERSION
          hub pull-request -m "rudder-transformer version change-$VERSION"